// packages/core/src/vue/SchemaErrorBoundary.vue
<script setup lang="ts">
/**
 * `<SchemaErrorBoundary>` — Vue counterpart of the React
 * `SchemaErrorBoundary`.
 *
 * Uses Vue 3's `onErrorCaptured` lifecycle hook
 * (https://vuejs.org/api/composition-api-lifecycle.html#onerrorcaptured)
 * to catch render-time errors thrown by any descendant — including
 * the dispatcher-wrapped `SchemaRenderError` from theme adapters that
 * throw inside their render function. Returning `false` from
 * `onErrorCaptured` halts further propagation up the component tree.
 *
 * The fallback slot is invoked with the captured error and a `reset`
 * callback. Calling `reset()` clears the captured error so the
 * children re-render (e.g. after fixing a bad schema prop).
 *
 * Like the React boundary, this captures render-time and lifecycle
 * errors but NOT errors thrown from event handlers (Vue routes those
 * through a separate `errorHandler` on the app instance) or async
 * code that escapes the component tree.
 *
 * @group Components
 */
import { onErrorCaptured, ref } from "vue";

const captured = ref<Error | undefined>(undefined);

defineSlots<{
    /**
     * Default slot — rendered when no error has been captured.
     */
    default(): unknown;
    /**
     * Fallback slot — invoked with the captured error and a `reset`
     * callback. Use it to render an error UI; call `reset` to clear
     * the captured state and let the children re-render.
     */
    fallback(props: { error: Error; reset: () => void }): unknown;
}>();

onErrorCaptured((err) => {
    captured.value =
        err instanceof Error ? err : new Error("Unknown render error");
    return false;
});

function reset(): void {
    captured.value = undefined;
}
</script>

<template>
    <slot
        v-if="captured !== undefined"
        name="fallback"
        :error="captured"
        :reset="reset"
    />
    <slot v-else />
</template>

// packages/core/src/react/SchemaErrorBoundary.tsx
"use client";

/**
 * React error boundary for schema-components.
 *
 * Catches render errors from `<SchemaComponent>`, theme adapters, and
 * any child components. Without this boundary, a throwing render function
 * crashes the entire React tree.
 *
 * Usage:
 *   import { SchemaErrorBoundary } from "schema-components/react/SchemaErrorBoundary";
 *
 *   <SchemaErrorBoundary fallback={(error) => <p>{error.message}</p>}>
 *     <SchemaComponent schema={userSchema} value={user} />
 *   </SchemaErrorBoundary>
 *
 * The boundary catches `SchemaRenderError` from theme adapters and any
 * other errors thrown during rendering. It does NOT catch:
 * - Event handler errors (onChange, etc.)
 * - Async errors
 * - Errors in server-side rendering
 */

import { Component, type ReactNode } from "react";
import { SchemaError } from "../core/errors.ts";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

/**
 * Props accepted by {@link SchemaErrorBoundary}.
 *
 * @group Components
 */
export interface SchemaErrorBoundaryProps {
    /** Called with the caught error. Returns fallback ReactNode to render. */
    fallback: (error: Error, reset: () => void) => ReactNode;
    children: ReactNode;
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

interface ErrorBoundaryState {
    error: Error | undefined;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * React error boundary that catches rendering errors from
 * `SchemaComponent`, theme adapters, and any descendant.
 *
 * Provides a `reset` callback that clears the error state, allowing
 * the children to re-render (e.g. after fixing a bad schema prop).
 * Does not catch errors thrown from event handlers, async work, or
 * server-side rendering — those paths must be handled by the host
 * application.
 *
 * @group Components
 * @example
 * ```tsx
 * <SchemaErrorBoundary fallback={(error) => <p>{error.message}</p>}>
 *   <SchemaComponent schema={userSchema} value={user} onChange={setUser} />
 * </SchemaErrorBoundary>
 * ```
 */
export class SchemaErrorBoundary extends Component<
    SchemaErrorBoundaryProps,
    ErrorBoundaryState
> {
    state: ErrorBoundaryState = { error: undefined };

    static getDerivedStateFromError(error: Error): ErrorBoundaryState {
        return { error };
    }

    componentDidCatch(error: Error): void {
        // If this is a SchemaError, the consumer's onError prop on
        // SchemaComponent already handled it. This boundary is for
        // render-time errors from theme adapters that escape that path.
        if (!(error instanceof SchemaError)) {
            console.error("[schema-components] Unhandled render error:", error);
        }
    }

    reset = (): void => {
        this.setState({ error: undefined });
    };

    render(): ReactNode {
        if (this.state.error !== undefined) {
            return this.props.fallback(this.state.error, this.reset);
        }
        return this.props.children;
    }
}
