// packages/core/src/vue/SchemaView.vue
<script setup lang="ts">
/**
 * `<SchemaView>` — read-only Vue renderer.
 *
 * Vue counterpart of `react/SchemaView.tsx`. Always renders read-only
 * output; the dispatch loop is identical to `<SchemaComponent>` but
 * the `onChange` callback handed to the dispatcher is a noop and
 * `mergedMeta.readOnly` is forced to `true`.
 *
 * SSR story: Vue ships a server renderer (`@vue/server-renderer`)
 * that emits HTML strings from the same render functions, so this
 * SFC is safe to use inside a Nuxt server component or a custom
 * `renderToString` pipeline. Unlike the React Server Component
 * version, there is no separate RSC restriction — Vue components
 * have a single rendering model that works in both environments.
 *
 * @group Components
 */
import { computed, h, toRaw, type VNode } from "vue";
import { walk } from "../core/walker.ts";
import type { WalkOptions } from "../core/walkBuilders.ts";
import { normaliseSchema } from "../core/adapter.ts";
import type { SchemaMeta, WalkedField } from "../core/types.ts";
import type { Diagnostic, DiagnosticsOptions } from "../core/diagnostics.ts";
import { SchemaNormalisationError } from "../core/errors.ts";
import { toRecordOrUndefined } from "../core/guards.ts";
import { vueRenderField } from "./renderField.ts";
import { deriveIdPrefix, joinPath } from "./idPrefix.ts";
import type {
    VueComponentResolver,
    VueRenderProps,
    VueWidgetMap,
} from "./types.ts";
import { VNodeHost } from "./VNodeHost.ts";

const props = withDefaults(
    defineProps<{
        /** Zod schema, JSON Schema object, or OpenAPI document. */
        schema: unknown;
        /** For OpenAPI: a ref string. */
        refPath?: string;
        /** Current value to render. */
        value?: unknown;
        /** Meta overrides applied to the root schema. */
        meta?: SchemaMeta;
        /** Convenience: sets `description` on the root. */
        description?: string;
        /** Per-field meta overrides — nested object mirroring schema shape. */
        fields?: Record<string, unknown>;
        /**
         * Theme resolver. In a Server Component environment you pass
         * this explicitly because the context-based `<SchemaProvider>`
         * may not be mounted on the server.
         */
        resolver?: VueComponentResolver;
        /** Instance-scoped widgets. */
        widgets?: VueWidgetMap;
        /** Deterministic id prefix. Defaults to a per-instance `useId()` value. */
        idPrefix?: string;
        /** Called with each diagnostic emitted during schema processing. */
        onDiagnostic?: (diagnostic: Diagnostic) => void;
        /** When `true`, any diagnostic becomes a thrown error. */
        strict?: boolean;
    }>(),
    {
        refPath: undefined,
        value: undefined,
        meta: () => ({}),
        description: undefined,
        fields: undefined,
        resolver: undefined,
        widgets: undefined,
        idPrefix: undefined,
        onDiagnostic: undefined,
        strict: false,
    }
);

const rootPath = computed(() => deriveIdPrefix(props.idPrefix));

const mergedMeta = computed<SchemaMeta>(() => {
    const merged: SchemaMeta = { ...props.meta, readOnly: true };
    if (props.description !== undefined) merged.description = props.description;
    return merged;
});

const diagnostics = computed<DiagnosticsOptions | undefined>(() => {
    if (props.onDiagnostic === undefined && !props.strict) return undefined;
    const opts: DiagnosticsOptions = {};
    if (props.onDiagnostic !== undefined) opts.diagnostics = props.onDiagnostic;
    if (props.strict) opts.strict = true;
    return opts;
});

interface Normalised {
    jsonSchema: Record<string, unknown>;
    rootMeta: SchemaMeta | undefined;
    rootDocument: Record<string, unknown>;
}

const normalised = computed<Normalised>(() => {
    const opts =
        diagnostics.value !== undefined
            ? { diagnostics: diagnostics.value }
            : undefined;
    try {
        // `toRaw` peels off Vue's reactive proxy before the schema
        // crosses into `normaliseSchema`, which expects the bare
        // object (Zod schemas in particular have non-configurable
        // `_zod` data members that Vue's default Proxy cannot mirror).
        // See the matching comment in `SchemaComponent.vue`.
        const rawSchema = toRaw(props.schema);
        const result = normaliseSchema(rawSchema, props.refPath, opts);
        return {
            jsonSchema: result.jsonSchema,
            rootMeta: result.rootMeta,
            rootDocument: result.rootDocument,
        };
    } catch (err) {
        if (err instanceof SchemaNormalisationError) throw err;
        throw new SchemaNormalisationError(
            err instanceof Error ? err.message : "Failed to normalise schema",
            toRaw(props.schema),
            "unknown"
        );
    }
});

const tree = computed<WalkedField>(() => {
    const n = normalised.value;
    const walkOptions: WalkOptions = {
        componentMeta: mergedMeta.value,
        rootDocument: n.rootDocument,
    };
    if (n.rootMeta !== undefined) walkOptions.rootMeta = n.rootMeta;
    const fieldsRecord = toRecordOrUndefined(props.fields);
    if (fieldsRecord !== undefined) walkOptions.fieldOverrides = fieldsRecord;
    if (diagnostics.value !== undefined)
        walkOptions.diagnostics = diagnostics.value;
    return walk(n.jsonSchema, walkOptions);
});

/** Noop onChange — SchemaView never propagates value changes. */
function noopChange(): void {
    /* intentional no-op */
}

function makeRenderChild(
    currentDepth: number,
    parentPath: string
): VueRenderProps["renderChild"] {
    return (
        childTree: WalkedField,
        childValue: unknown,
        _childOnChange: (v: unknown) => void,
        pathSuffix?: string
    ) => {
        const childPath = joinPath(parentPath, pathSuffix);
        return vueRenderField(
            childTree,
            childValue,
            noopChange,
            props.resolver,
            makeRenderChild(currentDepth + 1, childPath),
            childPath,
            props.widgets,
            undefined,
            currentDepth + 1
        );
    };
}

const rootVNode = computed<VNode>(() => {
    const t = tree.value;
    const renderChild = makeRenderChild(0, rootPath.value);
    return vueRenderField(
        t,
        props.value ?? t.defaultValue,
        noopChange,
        props.resolver,
        renderChild,
        rootPath.value,
        props.widgets,
        undefined,
        0
    );
});

// Silence the `h` import: kept available for downstream theme adapters
// that wrap `<SchemaView>` and need to compose extra structure around
// the render output. The SFC body itself only consumes the computed
// VNode through `<VNodeHost>`.
void h;
</script>

<template>
    <VNodeHost :node="rootVNode" />
</template>

// packages/core/src/react/SchemaView.tsx
/**
 * React Server Component for read-only schema rendering.
 *
 * Uses no React state, context, or effects — no `useContext`, `useMemo`,
 * `useCallback`, `useState`, or `useEffect`. The single hook called is
 * `useId()`, which is one of the few hooks permitted inside a React
 * Server Component (it is RSC-safe by design) and is used solely to
 * derive a stable per-instance `idPrefix`. The component therefore runs
 * in an RSC environment without the `"use client"` directive.
 *
 * **Read-only only.** For interactive forms with `onChange`, use
 * `<SchemaComponent>` (which requires `"use client"`).
 *
 * Usage in a Server Component:
 * ```tsx
 * import { SchemaView } from "schema-components/react/SchemaView";
 *
 * export default async function Page() {
 *   const user = await getUser();
 *   return <SchemaView schema={userSchema} value={user} />;
 * }
 * ```
 *
 * The `resolver` prop replaces the `SchemaProvider` context —
 * Server Components cannot use React context, so the resolver
 * is passed explicitly.
 */

import { createElement, isValidElement, useId, type ReactNode } from "react";
import type { ComponentResolver, RenderProps } from "../core/renderer.ts";
import {
    buildRenderProps,
    getRenderFunction,
    mergeResolvers,
} from "../core/renderer.ts";
import {
    joinPath,
    sanitisePrefix,
    type WidgetMap,
} from "./SchemaComponent.tsx";
import { headlessResolver } from "./headless.tsx";
import { normaliseSchema } from "../core/adapter.ts";
import { MAX_RENDER_DEPTH } from "../core/limits.ts";
import { walk } from "../core/walker.ts";
import type { WalkOptions } from "../core/walkBuilders.ts";
import type { SchemaMeta, WalkedField } from "../core/types.ts";
import { SchemaNormalisationError, SchemaRenderError } from "../core/errors.ts";
import type { DiagnosticsOptions, Diagnostic } from "../core/diagnostics.ts";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface SchemaViewProps {
    /** Zod schema, JSON Schema object, or OpenAPI document. */
    schema: unknown;
    /** For OpenAPI: a ref string like "#/components/schemas/User". */
    ref?: string;
    /** Current value to render. */
    value?: unknown;
    /** Per-field meta overrides. */
    fields?: Record<string, unknown>;
    /** Meta overrides applied to the root schema. */
    meta?: SchemaMeta;
    /** Convenience: sets description on the root. */
    description?: string;
    /**
     * Theme resolver. In a Server Component you pass this explicitly
     * since `SchemaProvider` (React context) is unavailable.
     * Falls back to the headless resolver if omitted.
     */
    resolver?: ComponentResolver;
    /** Instance-scoped widgets. */
    widgets?: WidgetMap;
    /** Called with each diagnostic emitted during schema processing. */
    onDiagnostic?: (diagnostic: Diagnostic) => void;
    /** When true, any diagnostic becomes a thrown error. */
    strict?: boolean;
    /**
     * Prefix used for every input `id`/label `htmlFor` in this view subtree.
     * Defaults to a per-instance value from `useId()`; pass a deterministic
     * value when stable ids matter (e.g. snapshot tests).
     */
    idPrefix?: string;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * Server-safe schema renderer — no context and no state. The only hook
 * called is `useId()`, which is RSC-safe.
 *
 * Always renders in read-only mode. For editable forms, use
 * `<SchemaComponent>` with `"use client"`.
 */
export function SchemaView({
    schema: schemaInput,
    ref: refInput,
    value,
    fields,
    meta: componentMeta,
    description,
    resolver,
    widgets,
    onDiagnostic,
    strict,
    idPrefix,
}: SchemaViewProps): ReactNode {
    const generatedId = useId();
    const rootPath = idPrefix ?? sanitisePrefix(generatedId);
    const mergedMeta: SchemaMeta = { ...componentMeta, readOnly: true };
    if (description !== undefined) mergedMeta.description = description;

    const diagnostics: DiagnosticsOptions | undefined =
        onDiagnostic !== undefined || strict === true
            ? {
                  ...(onDiagnostic !== undefined
                      ? { diagnostics: onDiagnostic }
                      : {}),
                  ...(strict !== undefined ? { strict } : {}),
              }
            : undefined;

    // Normalise input → JSON Schema
    let jsonSchema: Record<string, unknown>;
    let rootMeta: SchemaMeta | undefined;
    let rootDocument: Record<string, unknown>;
    try {
        const normalised = normaliseSchema(
            schemaInput,
            refInput,
            diagnostics !== undefined ? { diagnostics } : undefined
        );
        jsonSchema = normalised.jsonSchema;
        rootMeta = normalised.rootMeta;
        rootDocument = normalised.rootDocument;
    } catch (err: unknown) {
        // normaliseSchema already throws SchemaNormalisationError with the
        // correct kind. Only wrap genuinely unknown errors.
        if (err instanceof SchemaNormalisationError) throw err;
        throw new SchemaNormalisationError(
            err instanceof Error ? err.message : "Failed to normalise schema",
            schemaInput,
            "unknown"
        );
    }

    // Walk the JSON Schema tree
    const walkOptions: WalkOptions = {
        componentMeta: mergedMeta,
        rootMeta,
        fieldOverrides: fields,
        rootDocument,
        ...(diagnostics !== undefined ? { diagnostics } : {}),
    };

    const tree = walk(jsonSchema, walkOptions);

    // Build resolver: explicit prop → headless fallback
    const userResolver =
        resolver !== undefined
            ? mergeResolvers(resolver, headlessResolver)
            : headlessResolver;

    // Recursive render — no hooks, pure functions. Depth limit prevents
    // infinite recursion on circular schema references.
    const makeRenderChild =
        (currentDepth: number, parentPath: string) =>
        (
            childTree: WalkedField,
            childValue: unknown,
            pathSuffix?: string
        ): ReactNode => {
            const childPath = joinPath(parentPath, pathSuffix);
            if (currentDepth >= MAX_RENDER_DEPTH) {
                const label =
                    typeof childTree.meta.description === "string"
                        ? childTree.meta.description
                        : "schema";
                return createElement(
                    "fieldset",
                    null,
                    createElement("em", null, `\u21bb ${label} (recursive)`)
                );
            }
            return renderFieldServer(
                childTree,
                childValue,
                userResolver,
                makeRenderChild(currentDepth + 1, childPath),
                childPath,
                widgets
            );
        };

    const renderChild = makeRenderChild(0, rootPath);

    return renderFieldServer(
        tree,
        value ?? tree.defaultValue,
        userResolver,
        renderChild,
        rootPath,
        widgets
    );
}

// ---------------------------------------------------------------------------
// Field rendering — mirrors renderField from SchemaComponent but
// without hooks, error boundaries, or widget registry.
// ---------------------------------------------------------------------------

function renderFieldServer(
    tree: WalkedField,
    value: unknown,
    resolver: ComponentResolver,
    renderChild: (
        tree: WalkedField,
        value: unknown,
        pathSuffix?: string
    ) => ReactNode,
    path: string,
    widgets?: WidgetMap
): ReactNode {
    if (path.length === 0) {
        throw new Error(
            "renderFieldServer requires a non-empty path. Pass ROOT_PATH at the root and join children via joinPath()."
        );
    }
    // Adapt the read-only renderChild (3-arg) to the RenderProps shape
    // (4-arg). SchemaView discards child onChange because the tree is
    // rendered read-only.
    const adaptedRenderChild: RenderProps["renderChild"] = (
        childTree,
        childValue,
        _childOnChange,
        pathSuffix
    ) => renderChild(childTree, childValue, pathSuffix);

    // Check widgets before resolver — instance widgets take priority
    const componentHint = tree.meta.component;
    if (typeof componentHint === "string") {
        const widget = widgets?.get(componentHint);
        if (widget !== undefined) {
            const props = buildRenderProps(
                tree,
                value,
                undefined,
                adaptedRenderChild,
                path
            );
            const result: unknown = widget(props);
            if (result !== undefined && result !== null) {
                if (isValidElement(result)) return result;
                if (typeof result === "string" || typeof result === "number")
                    return result;
            }
        }
    }

    const renderFn = getRenderFunction(tree.type, resolver);

    if (renderFn !== undefined) {
        const props = buildRenderProps(
            tree,
            value,
            undefined,
            adaptedRenderChild,
            path
        );

        try {
            const result: unknown = renderFn(props);
            if (result !== undefined && result !== null) {
                if (isValidElement(result)) return result;
                if (typeof result === "string" || typeof result === "number")
                    return result;
            }
        } catch (err: unknown) {
            throw new SchemaRenderError(
                err instanceof Error
                    ? err.message
                    : `Render function threw for type "${tree.type}"`,
                tree,
                tree.type,
                err
            );
        }
    }

    // Fallback
    if (value === undefined || value === null) return <span>{"\u2014"}</span>;
    return (
        <span>{typeof value === "string" ? value : JSON.stringify(value)}</span>
    );
}
