// packages/core/src/lit/SchemaField.ts
/**
 * `<schema-field>` — Lit Custom Element rendering a single field from
 * a schema by dot-separated `path`.
 *
 * Parallel to React's `<SchemaField>`. The element walks the supplied
 * schema, resolves the field at `path`, and renders just that branch.
 * Useful for forms where the layout is hand-built and each field
 * needs its own renderer slot.
 *
 * Implementation note: `<schema-field>` extends `<schema-component>`
 * so the normalisation / dispatch logic is inherited. The override
 * here intercepts the post-walk tree and substitutes the path-
 * targeted branch.
 *
 * @packageDocumentation
 */

import { html, type TemplateResult } from "lit";
import { walk } from "../core/walker.ts";
import type { WalkOptions } from "../core/walkBuilders.ts";
import { normaliseSchema } from "../core/adapter.ts";
import type { SchemaMeta, WalkedField } from "../core/types.ts";
import { SchemaFieldError, SchemaNormalisationError } from "../core/errors.ts";
import { toRecordOrUndefined } from "../core/guards.ts";
import { isObject } from "../core/guards.ts";
import { createDefaultLitResolver } from "./defaultResolver.ts";
import { SchemaComponent } from "./SchemaComponent.ts";

/**
 * Lit Custom Element rendering a single sub-field of a schema.
 *
 * Tag: `<schema-field>` (registered by `registerSchemaComponents`).
 */
export class SchemaField extends SchemaComponent {
    /**
     * Dot-separated path identifying the field to render
     * (e.g. `"address.city"` or `"tags[0]"`).
     */
    path = "";

    static override readonly properties = {
        ...SchemaComponent.properties,
        path: { attribute: false },
    };

    override render(): TemplateResult {
        if (this.schema === undefined || this.path.length === 0) {
            return html``;
        }

        let jsonSchema: Record<string, unknown>;
        let rootMeta: SchemaMeta | undefined;
        let rootDocument: Record<string, unknown>;
        try {
            const normalised = normaliseSchema(this.schema, this.ref);
            jsonSchema = normalised.jsonSchema;
            rootMeta = normalised.rootMeta;
            rootDocument = normalised.rootDocument;
        } catch (err: unknown) {
            if (err instanceof SchemaNormalisationError) throw err;
            throw new SchemaNormalisationError(
                err instanceof Error
                    ? err.message
                    : "Failed to normalise schema",
                this.schema,
                "unknown"
            );
        }

        const walkOptions: WalkOptions = {
            componentMeta: this.meta,
            rootMeta,
            fieldOverrides: toRecordOrUndefined(this.fields),
            rootDocument,
        };
        const root = walk(jsonSchema, walkOptions);
        const located = locateField(root, this.path);
        if (located === undefined) {
            throw new SchemaFieldError(
                `No field at path ${this.path}`,
                root,
                this.path
            );
        }
        const { tree, value } = located;
        const valueToRender = value ?? tree.defaultValue;
        const userResolver = this.resolver ?? createDefaultLitResolver();
        const renderChild = this.makeRenderChild(0, this.path, userResolver);
        return this.renderField(
            tree,
            valueToRender,
            (next) => {
                this.dispatchEvent(
                    new CustomEvent("change", {
                        detail: { value: next, path: this.path },
                    })
                );
            },
            userResolver,
            renderChild,
            this.path
        );
    }
}

// ---------------------------------------------------------------------------
// Path resolution — pure helpers, kept inline so the layer-boundary lint
// doesn't have to gain a `lit → react` exception just for fieldPath.
// ---------------------------------------------------------------------------

/**
 * Resolve a dot-separated path through a walked field tree, also
 * tracking the value at the same position. Mirrors
 * `react/fieldPath.ts::resolvePath` + `resolveValue` rolled into one.
 *
 * @internal
 */
function locateField(
    root: WalkedField,
    path: string
): { tree: WalkedField; value: unknown } | undefined {
    const segments = splitPath(path);
    let currentTree: WalkedField = root;
    let currentValue: unknown = undefined;
    for (const segment of segments) {
        const numericIndex = parseIndex(segment);
        if (numericIndex !== undefined) {
            if (currentTree.type === "array" && currentTree.element) {
                currentTree = currentTree.element;
                currentValue = Array.isArray(currentValue)
                    ? currentValue[numericIndex]
                    : undefined;
                continue;
            }
            if (currentTree.type === "tuple") {
                const next = currentTree.prefixItems[numericIndex];
                if (next === undefined) return undefined;
                currentTree = next;
                currentValue = Array.isArray(currentValue)
                    ? currentValue[numericIndex]
                    : undefined;
                continue;
            }
            return undefined;
        }
        if (currentTree.type === "object") {
            const next = currentTree.fields[segment];
            if (next === undefined) return undefined;
            currentTree = next;
            currentValue = isObject(currentValue)
                ? currentValue[segment]
                : undefined;
            continue;
        }
        if (currentTree.type === "record") {
            currentTree = currentTree.valueType;
            currentValue = isObject(currentValue)
                ? currentValue[segment]
                : undefined;
            continue;
        }
        return undefined;
    }
    return { tree: currentTree, value: currentValue };
}

/**
 * Split a dot-separated path with bracketed indices into its
 * structural segments. `"a.b[0].c"` → `["a", "b", "[0]", "c"]`.
 */
function splitPath(path: string): string[] {
    const out: string[] = [];
    let current = "";
    for (const ch of path) {
        if (ch === ".") {
            if (current.length > 0) {
                out.push(current);
                current = "";
            }
            continue;
        }
        if (ch === "[") {
            if (current.length > 0) {
                out.push(current);
            }
            current = "[";
            continue;
        }
        if (ch === "]") {
            current += "]";
            out.push(current);
            current = "";
            continue;
        }
        current += ch;
    }
    if (current.length > 0) out.push(current);
    return out;
}

/**
 * Parse a `[i]` bracketed-index segment to a number. Returns
 * `undefined` for non-numeric or non-bracketed input.
 */
function parseIndex(segment: string): number | undefined {
    if (!segment.startsWith("[") || !segment.endsWith("]")) return undefined;
    const inner = segment.slice(1, -1);
    if (inner.length === 0) return undefined;
    const n = Number(inner);
    if (!Number.isInteger(n) || n < 0) return undefined;
    return n;
}

// packages/core/src/vue/SchemaField.vue
<script setup lang="ts">
/**
 * `<SchemaField>` — render a single field from a schema by dot-separated
 * path.
 *
 * Vue counterpart of `react/SchemaComponent.tsx`'s `<SchemaField>`.
 * Walks the full schema tree and resolves the field at the supplied
 * `path`, then renders only that field through the same Vue resolver
 * pipeline as `<SchemaComponent>`.
 *
 * Useful for embedding individual fields inside bespoke layouts (e.g.
 * a custom Vue form that lays out address fields manually but still
 * wants the schema-driven rendering for each).
 *
 * @group Components
 */
import { computed, toRaw, type VNode } from "vue";
import { walk } from "../core/walker.ts";
import type { WalkOptions } from "../core/walkBuilders.ts";
import { normaliseSchema } from "../core/adapter.ts";
import {
    resolvePath,
    resolveValue,
    setNestedValue,
} from "../core/fieldPath.ts";
import type { SchemaMeta, WalkedField } from "../core/types.ts";
import {
    SchemaFieldError,
    SchemaNormalisationError,
} from "../core/errors.ts";
import { VueResolverContext, VueWidgetsContext } from "./contexts.ts";
import { vueRenderField } from "./renderField.ts";
import { deriveIdPrefix, joinPath } from "./idPrefix.ts";
import type { VueRenderProps } from "./types.ts";
import { VNodeHost } from "./VNodeHost.ts";

const props = withDefaults(
    defineProps<{
        /** Dot-separated path to the field (e.g. `"address.city"`). */
        path: string;
        /** The schema to extract the field from. */
        schema: unknown;
        /** For OpenAPI: a ref string. */
        refPath?: string;
        /** Current value of the root object the field belongs to. */
        modelValue?: unknown;
        /** Explicit onChange callback. Wired alongside `update:modelValue`. */
        onChange?: (value: unknown) => void;
        /** Override meta for this specific field. */
        meta?: SchemaMeta;
        /** Deterministic id prefix. Defaults to a per-instance `useId()` value. */
        idPrefix?: string;
    }>(),
    {
        refPath: undefined,
        modelValue: undefined,
        onChange: undefined,
        meta: () => ({}),
        idPrefix: undefined,
    }
);

const emit = defineEmits<{
    "update:modelValue": [value: unknown];
    change: [value: unknown];
}>();

const contextResolver = VueResolverContext.consume();
const contextWidgets = VueWidgetsContext.consume();

interface Normalised {
    jsonSchema: Record<string, unknown>;
    rootMeta: SchemaMeta | undefined;
    rootDocument: Record<string, unknown>;
}

const normalised = computed<Normalised>(() => {
    try {
        // See the matching `toRaw` note in `SchemaComponent.vue` —
        // Zod schemas carry non-configurable members that Vue's
        // default reactive Proxy cannot mirror.
        const rawSchema = toRaw(props.schema);
        const result = normaliseSchema(rawSchema, props.refPath);
        return {
            jsonSchema: result.jsonSchema,
            rootMeta: result.rootMeta,
            rootDocument: result.rootDocument,
        };
    } catch (err) {
        if (err instanceof SchemaNormalisationError) throw err;
        throw new SchemaNormalisationError(
            err instanceof Error ? err.message : "Failed to normalise schema",
            toRaw(props.schema),
            "unknown"
        );
    }
});

const fullTree = computed<WalkedField>(() => {
    const n = normalised.value;
    const walkOptions: WalkOptions = {
        componentMeta: props.meta,
        rootDocument: n.rootDocument,
    };
    if (n.rootMeta !== undefined) walkOptions.rootMeta = n.rootMeta;
    return walk(n.jsonSchema, walkOptions);
});

const fieldTree = computed<WalkedField>(() => {
    const found = resolvePath(fullTree.value, props.path);
    if (found === undefined) {
        throw new SchemaFieldError(
            `Field not found: ${props.path}`,
            toRaw(props.schema),
            props.path
        );
    }
    return found;
});

const fieldValue = computed<unknown>(() =>
    resolveValue(props.modelValue, props.path)
);

const rootBase = computed(() => deriveIdPrefix(props.idPrefix));
const rootPath = computed(() => joinPath(rootBase.value, props.path));

function handleFieldChange(nextField: unknown): void {
    const newRoot = setNestedValue(props.modelValue, props.path, nextField);
    emit("update:modelValue", newRoot);
    emit("change", newRoot);
    props.onChange?.(newRoot);
}

function makeRenderChild(
    currentDepth: number,
    parentPath: string
): VueRenderProps["renderChild"] {
    return (
        childTree: WalkedField,
        childValue: unknown,
        childOnChange: (v: unknown) => void,
        pathSuffix?: string
    ) => {
        const childPath = joinPath(parentPath, pathSuffix);
        return vueRenderField(
            childTree,
            childValue,
            childOnChange,
            contextResolver,
            makeRenderChild(currentDepth + 1, childPath),
            childPath,
            undefined,
            contextWidgets,
            currentDepth + 1
        );
    };
}

const rootVNode = computed<VNode>(() => {
    const renderChild = makeRenderChild(0, rootPath.value);
    return vueRenderField(
        fieldTree.value,
        fieldValue.value,
        handleFieldChange,
        contextResolver,
        renderChild,
        rootPath.value,
        undefined,
        contextWidgets,
        0
    );
});
</script>

<template>
    <VNodeHost :node="rootVNode" />
</template>
