// packages/core/src/lit/types.ts
/**
 * Lit / Web Components adapter — render-function and resolver contracts.
 *
 * Mirrors the shape of `ComponentResolver` (React) and `HtmlResolver`
 * (HTML-string) defined in `core/renderer.ts`, but specialised over Lit's
 * `TemplateResult`. The contract is intentionally parallel so a new schema
 * field variant added to the walker surfaces in every renderer surface
 * (React, HTML, Lit) as a missing-key compile error in the matching
 * resolver type.
 *
 * @packageDocumentation
 */

import type { TemplateResult } from "lit";
import type { AllConstraints } from "../core/renderer.ts";
import type { SchemaMeta, WalkedField } from "../core/types.ts";

// ---------------------------------------------------------------------------
// Render props
// ---------------------------------------------------------------------------

/**
 * Props handed to a Lit render function.
 *
 * Shares the same per-field data as `RenderProps` (React) and
 * `HtmlRenderProps` (HTML-string) but with a `renderChild` typed
 * over Lit's {@link TemplateResult}. Editable fields receive a
 * `change` callback that emits a Custom Event up the DOM tree —
 * unlike React's prop-callback model, Custom Elements communicate via
 * DOM events, so the renderer wires the input event to a
 * `dispatchEvent(new CustomEvent("sc-change", { detail: { value } }))`
 * on the host element.
 *
 * Renderers narrow on `tree.type` for per-variant data
 * (object fields, array element schema, union options, etc.) — the
 * walker's discriminated union enforces type-correct access.
 */
export interface LitRenderProps {
    /** Current field value. */
    value: unknown;
    /** Whether to render as read-only display. */
    readOnly: boolean;
    /** Whether to render as an empty input. */
    writeOnly: boolean;
    /** Schema metadata for this field. */
    meta: SchemaMeta;
    /** Constraints from schema checks. */
    constraints: AllConstraints;
    /** Dot-separated path from root (e.g. "address.city"). */
    path: string;
    /** Example values from the schema's `examples` keyword. */
    examples?: unknown[];
    /** Walked field tree for recursive rendering. */
    tree: WalkedField;
    /**
     * Callback to propagate the next value back to the host element.
     *
     * Renderers wire DOM events (`@input`, `@change`, `@click` on add /
     * remove controls) to this callback. The host element catches the
     * resulting change and emits a `change` Custom Event on itself so
     * framework consumers can observe via standard `addEventListener`.
     */
    change: (value: unknown) => void;
    /**
     * Render a child field. Resolver overrides call this to recursively
     * render nested structures (object fields, array elements, union
     * options) without re-running the resolver dispatch loop.
     *
     * @param tree - The walked field tree for the child
     * @param value - The child's current value
     * @param change - Callback receiving the child's next value
     * @param pathSuffix - Path segment from the parent (e.g. `city` for
     *   an object key, `[0]` for an array index). Required for every
     *   container — without it children inherit no path and DOM id
     *   derivation throws.
     */
    renderChild: (
        tree: WalkedField,
        value: unknown,
        change: (next: unknown) => void,
        pathSuffix?: string
    ) => TemplateResult;
}

// ---------------------------------------------------------------------------
// Render function
// ---------------------------------------------------------------------------

/**
 * Signature for a Lit render function attached to a
 * {@link LitComponentResolver}. Receives the per-field
 * {@link LitRenderProps} built by the walker and returns a Lit
 * {@link TemplateResult} for direct interpolation into the host
 * element's `render()` method.
 *
 * The return type is `TemplateResult`, the type produced by
 * the `html`-tagged template literal. Unlike `RenderFunction` (React)
 * which returns `unknown` so React elements, primitive children, and
 * arbitrary value types can flow through, Lit templates have a single
 * canonical type — narrowing makes the resolver dispatch loop simpler
 * and forces every renderer to return a structurally compatible value.
 */
export type LitRenderFunction = (props: LitRenderProps) => TemplateResult;

// ---------------------------------------------------------------------------
// Resolver
// ---------------------------------------------------------------------------

/**
 * Theme adapter — maps every schema field type to its Lit renderer.
 *
 * Structurally mirrors `ComponentResolver` (React) and `HtmlResolver`
 * (HTML-string) so the resolver-key tuple in `core/renderer.ts`
 * (`RESOLVER_KEYS`) drives every dispatch surface from a single
 * source-of-truth list.
 *
 * Unset keys fall through to the default Lit resolver
 * (`defaultLitResolver` in `lit/renderers/registry.ts`). The default
 * resolver is composed from the built-in `<sc-*>` Custom Elements
 * registered by {@link registerSchemaComponents} — overriding a key
 * here lets a consumer bypass the Custom Element registry for a
 * specific schema type without unregistering the element.
 */
export interface LitComponentResolver {
    string?: LitRenderFunction;
    number?: LitRenderFunction;
    boolean?: LitRenderFunction;
    null?: LitRenderFunction;
    enum?: LitRenderFunction;
    object?: LitRenderFunction;
    array?: LitRenderFunction;
    tuple?: LitRenderFunction;
    record?: LitRenderFunction;
    union?: LitRenderFunction;
    discriminatedUnion?: LitRenderFunction;
    conditional?: LitRenderFunction;
    negation?: LitRenderFunction;
    literal?: LitRenderFunction;
    file?: LitRenderFunction;
    never?: LitRenderFunction;
    unknown?: LitRenderFunction;
}

// ---------------------------------------------------------------------------
// Type test — Lit render function composes with the core RenderFunction
// shape, parameterised over output type.
// ---------------------------------------------------------------------------

/**
 * Compile-time witness that {@link LitRenderFunction} is a
 * `(props: P) => O` shape exactly matching the parallel signatures
 * carried by `core/renderer.ts`. The walker's dispatch loop is
 * parameterised over `O` (React's `unknown`, HTML's `string`, Lit's
 * `TemplateResult`) and `P` (the matching per-renderer props), so this
 * alias documents the contract without forcing `core/renderer.ts` to
 * import Lit.
 *
 * @internal
 */
export type _LitFunctionShapeAssertion = LitRenderFunction extends (
    props: LitRenderProps
) => TemplateResult
    ? true
    : false;

// packages/core/src/solid/types.ts
/**
 * Solid-flavoured renderer types.
 *
 * Mirrors the React adapter's `RenderProps` / `RenderFunction` /
 * `ComponentResolver` triple, but specialised for Solid:
 *
 * - The renderer's output type is `JSX.Element` from `solid-js`.
 * - There is no synthetic event system in Solid — `onChange` receives the
 *   next value directly, exactly as on React.
 * - There are no per-render hooks; renderers consume their props through
 *   ordinary destructuring or `props.x` access.
 *
 * Per-type schema data lives on the discriminated `tree` (mirroring
 * core/renderer.ts) — renderers narrow on `tree.type` and read from the
 * matching variant.
 */

import type { JSX } from "solid-js";
import type {
    AllConstraints,
    BaseFieldProps,
    RenderFunction,
} from "../core/renderer.ts";
import type { WalkedField } from "../core/types.ts";

// `AllConstraints` is re-exported through the renderer surface so the
// Solid layer doesn't need a parallel definition; importing it explicitly
// here is documentation only.
export type { AllConstraints };

/**
 * Per-field props handed to a Solid render function.
 *
 * Mirrors React's `RenderProps` shape (the contract is identical at the
 * data layer) but the `renderChild` return type is Solid's `JSX.Element`
 * rather than React's `ReactNode`. The walker, path threading,
 * constraint extraction, and union heuristics are all shared with the
 * React adapter.
 */
export interface SolidRenderProps extends BaseFieldProps {
    /** Callback to update the field value. */
    onChange: (value: unknown) => void;
    /**
     * Render a child field. Theme adapters call this to recursively
     * render nested structures (object fields, array elements, union
     * options). The Solid resolver and rendering context are already
     * wired in.
     *
     * @param tree - The walked field tree for the child.
     * @param value - The child's current value.
     * @param onChange - Callback receiving the child's next value.
     * @param pathSuffix - Path segment from the parent (e.g. `"city"`,
     *   `"[0]"`). Joined to the parent's path with a dot, or
     *   substituted when the parent acts as a transparent wrapper
     *   (union options). Required for every container — without it
     *   children inherit no path and `fieldDomId()` returns the bare
     *   prefix.
     */
    renderChild: (
        tree: WalkedField,
        value: unknown,
        onChange: (v: unknown) => void,
        pathSuffix?: string
    ) => JSX.Element;
}

/**
 * Signature for a Solid render function attached to a
 * {@link SolidComponentResolver}. Specialises the generic
 * {@link RenderFunction} from `core/renderer.ts` with Solid's `JSX.Element`
 * output and the Solid-flavoured {@link SolidRenderProps} props.
 *
 * The compile-time relationship
 *
 * ```ts
 * type Check = SolidRenderFunction extends RenderFunction<JSX.Element, SolidRenderProps>
 *     ? true
 *     : false; // → true
 * ```
 *
 * holds by construction — the Solid renderer plugs into the generic
 * core contract without any per-framework escape hatch.
 */
export type SolidRenderFunction = RenderFunction<JSX.Element, SolidRenderProps>;

/**
 * Theme adapter — maps every schema field type to its Solid renderer.
 * Unset keys fall back to the headless resolver (see
 * `solid/headless.ts`). Pass to `<SchemaProvider resolver={...}>` to
 * drive every schema-driven render with a specific theme.
 *
 * Structurally mirrors React's `ComponentResolver` from
 * `core/renderer.ts` — Solid and React share the renderer key matrix
 * because both consume the same `WalkedField` discriminated union.
 */
export interface SolidComponentResolver {
    string?: SolidRenderFunction;
    number?: SolidRenderFunction;
    boolean?: SolidRenderFunction;
    null?: SolidRenderFunction;
    enum?: SolidRenderFunction;
    object?: SolidRenderFunction;
    array?: SolidRenderFunction;
    tuple?: SolidRenderFunction;
    record?: SolidRenderFunction;
    union?: SolidRenderFunction;
    discriminatedUnion?: SolidRenderFunction;
    conditional?: SolidRenderFunction;
    negation?: SolidRenderFunction;
    literal?: SolidRenderFunction;
    file?: SolidRenderFunction;
    never?: SolidRenderFunction;
    unknown?: SolidRenderFunction;
}

/**
 * Widget map for Solid — maps `.meta({ component: <name> })` hints to
 * per-instance render functions. Identical contract to the React widget
 * map; only the per-frame element type differs.
 */
export type SolidWidgetMap = ReadonlyMap<string, SolidRenderFunction>;
