// packages/core/src/react/SchemaErrorBoundary.tsx
"use client";

/**
 * React error boundary for schema-components.
 *
 * Catches render errors from `<SchemaComponent>`, theme adapters, and
 * any child components. Without this boundary, a throwing render function
 * crashes the entire React tree.
 *
 * Usage:
 *   import { SchemaErrorBoundary } from "schema-components/react/SchemaErrorBoundary";
 *
 *   <SchemaErrorBoundary fallback={(error) => <p>{error.message}</p>}>
 *     <SchemaComponent schema={userSchema} value={user} />
 *   </SchemaErrorBoundary>
 *
 * The boundary catches `SchemaRenderError` from theme adapters and any
 * other errors thrown during rendering. It does NOT catch:
 * - Event handler errors (onChange, etc.)
 * - Async errors
 * - Errors in server-side rendering
 */

import { Component, type ReactNode } from "react";
import { SchemaError } from "../core/errors.ts";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

/**
 * Props accepted by {@link SchemaErrorBoundary}.
 *
 * @group Components
 */
export interface SchemaErrorBoundaryProps {
    /** Called with the caught error. Returns fallback ReactNode to render. */
    fallback: (error: Error, reset: () => void) => ReactNode;
    children: ReactNode;
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

interface ErrorBoundaryState {
    error: Error | undefined;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * React error boundary that catches rendering errors from
 * `SchemaComponent`, theme adapters, and any descendant.
 *
 * Provides a `reset` callback that clears the error state, allowing
 * the children to re-render (e.g. after fixing a bad schema prop).
 * Does not catch errors thrown from event handlers, async work, or
 * server-side rendering — those paths must be handled by the host
 * application.
 *
 * @group Components
 * @example
 * ```tsx
 * <SchemaErrorBoundary fallback={(error) => <p>{error.message}</p>}>
 *   <SchemaComponent schema={userSchema} value={user} onChange={setUser} />
 * </SchemaErrorBoundary>
 * ```
 */
export class SchemaErrorBoundary extends Component<
    SchemaErrorBoundaryProps,
    ErrorBoundaryState
> {
    state: ErrorBoundaryState = { error: undefined };

    static getDerivedStateFromError(error: Error): ErrorBoundaryState {
        return { error };
    }

    componentDidCatch(error: Error): void {
        // If this is a SchemaError, the consumer's onError prop on
        // SchemaComponent already handled it. This boundary is for
        // render-time errors from theme adapters that escape that path.
        if (!(error instanceof SchemaError)) {
            console.error("[schema-components] Unhandled render error:", error);
        }
    }

    reset = (): void => {
        this.setState({ error: undefined });
    };

    render(): ReactNode {
        if (this.state.error !== undefined) {
            return this.props.fallback(this.state.error, this.reset);
        }
        return this.props.children;
    }
}

// packages/core/src/svelte/SchemaErrorBoundary.svelte
<!--
    Svelte 5 error boundary for schema-components.

    Uses Svelte 5's native `<svelte:boundary>` primitive (introduced
    in Svelte 5) — the structural equivalent of the React class
    component `componentDidCatch` / `getDerivedStateFromError`
    pattern from `react/SchemaErrorBoundary.tsx`.

    Catches synchronous render errors thrown by descendant
    components (including `<SchemaComponent>` / `<SchemaView>` and
    any custom theme adapter renderers). The boundary surfaces the
    caught `Error` to the supplied `fallback` snippet alongside a
    `reset` callback that clears the error state — Svelte's boundary
    primitive owns the state internally; the snippet just receives
    whichever helpers Svelte passes to it.

    Mirrors the React boundary's documentation: this primitive does
    NOT catch errors thrown from event handlers, async work, or
    server-side rendering. Those must be handled at the host
    application boundary.
-->
<script lang="ts">
    import type { Snippet } from "svelte";
    import { SchemaError } from "../core/errors.ts";

    interface Props {
        /** Rendered while no error is in flight. */
        children: Snippet;
        /**
         * Rendered when the boundary catches an error. Receives the
         * thrown `Error` and a `reset` thunk that re-renders the
         * children once the underlying problem is fixed (e.g. a
         * corrected `schema` prop).
         */
        fallback: Snippet<[Error, () => void]>;
    }

    const { children, fallback }: Props = $props();

    function logIfUnexpected(error: unknown): void {
        // Non-SchemaError thrown values are forwarded to the
        // console so the application has at least one signal in the
        // logs. SchemaError instances are presumed handled by the
        // `onError` callback on `<SchemaComponent>` / `<SchemaView>`.
        if (!(error instanceof SchemaError)) {
            // Diagnostic surface mirroring the React adapter — the
            // boundary's contract is "log the unexpected, surface
            // structured errors through `failed`".
            console.error("[schema-components] Unhandled render error:", error);
        }
    }
</script>

<svelte:boundary
    onerror={(error) => {
        logIfUnexpected(error);
    }}
>
    {@render children()}
    {#snippet failed(error, reset)}
        {@render fallback(
            error instanceof Error ? error : new Error(String(error)),
            reset
        )}
    {/snippet}
</svelte:boundary>
